### ISSUE TITLE
make install fails

### ISSUE THREAD

**Issue by patty-cake** [kgretzky/pwndrop#5] opened 2020-04-17 00:08 UTC
make install target attempts to stop a currently running instance, fails if there is not an instance running.

**Comment by kgretzky** [comment] 2020-04-17 07:19
Can you post a screenshot of that happening? I can't reproduce. Here is my output when trying `make install` after I stopped pwndrop first:
![image](https://user-images.githubusercontent.com/19260967/79542758-7e3e2480-808c-11ea-8368-f15940531435.png)

**Comment by patty-cake** [comment] 2020-04-17 13:31
![pwndrop_make_install_full](https://user-images.githubusercontent.com/28570727/79574260-e17c8680-808d-11ea-92b7-e87eec25f7a9.png)

This is in a fresh docker container that I setup to play with this.

**Comment by kgretzky** [comment] 2020-04-18 12:23
Thank you for reporting!

Fixed in f7af8e6d796ac4576d05922bc456ba845f7ee58d

**Closed by kgretzky** 2020-04-18 12:23 UTC
Labels: fixed
